name: Automatização de dataProcess.py

on:
  schedule:
    - cron: '*/5 * * * *' # Executa a cada 5 minutos

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Executar dataProcess.py
        run: |
          python src/integration_zoom/dataProcess.py
